[workspace]
members = ["common", "exchange", "trading"]
resolver = "2"

[workspace.dependencies]
criterion = "0.5"
common = { path = "common" }
exchange = { path = "exchange" }
trading = { path = "trading" }
